### ISSUE TITLE
Return 404 error

### ISSUE THREAD

**Issue by GovindaPaliwal** [simonesestito/shops-queue-php#1]
hi
Awesome app. could you help me on about this error.

It's return error on index.php.

`{"error":true,"status":404,"message":""}`

Thanks

**Comment by simonesestito** [comment]
The server needs to be configured appropriately to redirect all the traffic to the index.php file

You can run the project using the development PHP server:

```
cd <path to the src/ directory>
php -S localhost:1234
```

Then, you'll be able to execute the endpoints documented in Postman, prefixing their URI with `http://localhost:1234` (without "index.php")

Of course you need to set up the SQL database according to the **db.sql** file, and the environment variables as in the **src/env.php** file

**Comment by simonesestito** [comment]
Hi, I've added a [docker-compose.yml](https://github.com/simonesestito/shops-queue-php/blob/master/docker-compose.yml) file to this project in order to simplify its execution due to not so straightforward web server configuration.

I know it's been 2 years now, but I wanted to add it regardless of it maybe not being so useful anymore. It's primarily for myself to keep order. 

Of course, it's still necessary to execute the [db.sql](https://github.com/simonesestito/shops-queue-php/blob/master/db.sql) file inside of the DB Docker container. As always, reviewing the .env file is highly encouraged.

Finally, it's worth mentioning to say that it **must** be used with the appropriate Android app, which is open source as well and can be found at https://github.com/simonesestito/shops-queue-android (the compiled APK is using a live hosted version of the open source backend).

Thank you!
